services:
  banco_dados:
    image: postgres:15
    container_name: clima_db
    restart: always
    environment:
      POSTGRES_USER: usuario_dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: historico_clima
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data

volumes:
  dados_postgres: